#!/usr/bin/env node

import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
  ErrorCode,
  McpError,
} from "@modelcontextprotocol/sdk/types.js";
import { exec } from "child_process";
import { promisify } from "util";
import * as fs from "fs/promises";
import * as path from "path";
import * as os from "os";

const execAsync = promisify(exec);

// Configuration
const KALI_HOST = process.env.PROXYCHAINS_KALI_HOST || "kali";
const SSH_TIMEOUT = parseInt(process.env.PROXYCHAINS_SSH_TIMEOUT || "30000", 10);
const CONFIG_DIR = process.env.PROXYCHAINS_CONFIG_DIR || path.join(os.homedir(), ".proxychains-mcp");

// Types
type ChainMode = "strict_chain" | "dynamic_chain" | "random_chain" | "round_robin_chain";
type ProxyType = "http" | "socks4" | "socks5" | "raw";
type DnsMode = "proxy_dns" | "proxy_dns_old" | "proxy_dns_daemon" | "none";

interface Proxy {
  type: ProxyType;
  host: string;
  port: number;
  user?: string;
  pass?: string;
}

interface ProxychainsConfig {
  chainMode: ChainMode;
  dnsMode: DnsMode;
  chainLen?: number;
  tcpReadTimeout?: number;
  tcpConnectTimeout?: number;
  quiet?: boolean;
  proxies: Proxy[];
}

// Default configuration
const defaultConfig: ProxychainsConfig = {
  chainMode: "dynamic_chain",
  dnsMode: "proxy_dns",
  tcpReadTimeout: 15000,
  tcpConnectTimeout: 8000,
  quiet: true,
  proxies: [],
};

// Storage for current configuration
let currentConfig: ProxychainsConfig = { ...defaultConfig };

// Helper functions
async function ensureConfigDir(): Promise<void> {
  try {
    await fs.mkdir(CONFIG_DIR, { recursive: true });
  } catch (error) {
    // Directory might already exist
  }
}

async function loadConfig(): Promise<ProxychainsConfig> {
  try {
    const configPath = path.join(CONFIG_DIR, "config.json");
    const data = await fs.readFile(configPath, "utf-8");
    currentConfig = { ...defaultConfig, ...JSON.parse(data) };
    return currentConfig;
  } catch {
    return currentConfig;
  }
}

async function saveConfig(): Promise<void> {
  await ensureConfigDir();
  const configPath = path.join(CONFIG_DIR, "config.json");
  await fs.writeFile(configPath, JSON.stringify(currentConfig, null, 2));
}

function generateProxychainsConf(): string {
  const lines: string[] = [
    "# ProxyChains-ng configuration generated by proxychains-mcp",
    "",
  ];

  // Chain mode
  lines.push(`${currentConfig.chainMode}`);
  lines.push("");

  // DNS settings
  if (currentConfig.dnsMode !== "none") {
    lines.push(currentConfig.dnsMode);
  }
  lines.push("");

  // Timeouts
  if (currentConfig.tcpReadTimeout) {
    lines.push(`tcp_read_time_out ${currentConfig.tcpReadTimeout}`);
  }
  if (currentConfig.tcpConnectTimeout) {
    lines.push(`tcp_connect_time_out ${currentConfig.tcpConnectTimeout}`);
  }
  lines.push("");

  // Chain length (for random/round_robin modes)
  if (
    currentConfig.chainLen &&
    (currentConfig.chainMode === "random_chain" ||
      currentConfig.chainMode === "round_robin_chain")
  ) {
    lines.push(`chain_len = ${currentConfig.chainLen}`);
    lines.push("");
  }

  // Proxy list
  lines.push("[ProxyList]");
  for (const proxy of currentConfig.proxies) {
    let proxyLine = `${proxy.type}\t${proxy.host}\t${proxy.port}`;
    if (proxy.user) {
      proxyLine += `\t${proxy.user}`;
      if (proxy.pass) {
        proxyLine += `\t${proxy.pass}`;
      }
    }
    lines.push(proxyLine);
  }

  return lines.join("\n");
}

async function executeOnKali(
  command: string,
  timeout: number = SSH_TIMEOUT
): Promise<{ stdout: string; stderr: string }> {
  try {
    const result = await execAsync(`ssh ${KALI_HOST} "${command.replace(/"/g, '\\"')}"`, {
      timeout,
    });
    return result;
  } catch (error: any) {
    throw new McpError(
      ErrorCode.InternalError,
      `SSH command failed: ${error.message}`
    );
  }
}

async function runWithProxychains(
  command: string,
  customConfig?: string
): Promise<{ stdout: string; stderr: string }> {
  let sshCommand: string;

  if (customConfig) {
    // Write temp config and use it
    const tempConfig = `/tmp/proxychains_${Date.now()}.conf`;
    const escapedConfig = customConfig.replace(/'/g, "'\\''");
    sshCommand = `echo '${escapedConfig}' > ${tempConfig} && proxychains4 -q -f ${tempConfig} ${command} ; rm -f ${tempConfig}`;
  } else {
    // Generate config from current settings
    const config = generateProxychainsConf();
    const tempConfig = `/tmp/proxychains_${Date.now()}.conf`;
    const escapedConfig = config.replace(/'/g, "'\\''");
    sshCommand = `echo '${escapedConfig}' > ${tempConfig} && proxychains4 -q -f ${tempConfig} ${command} ; rm -f ${tempConfig}`;
  }

  return executeOnKali(sshCommand, SSH_TIMEOUT * 2);
}

// Create MCP Server
const server = new Server(
  {
    name: "proxychains-mcp",
    version: "1.0.0",
  },
  {
    capabilities: {
      tools: {},
    },
  }
);

// Define tools
server.setRequestHandler(ListToolsRequestSchema, async () => {
  return {
    tools: [
      {
        name: "proxychains_run",
        description:
          "Run a command through the proxy chain on Kali Linux. The command will be routed through all configured proxies.",
        inputSchema: {
          type: "object",
          properties: {
            command: {
              type: "string",
              description: "The command to run through proxychains (e.g., 'curl https://example.com', 'nmap -sT target')",
            },
            timeout: {
              type: "number",
              description: "Timeout in milliseconds (default: 60000)",
            },
          },
          required: ["command"],
        },
      },
      {
        name: "proxychains_config",
        description:
          "Get or set the current proxychains configuration including chain mode, DNS settings, and proxy list.",
        inputSchema: {
          type: "object",
          properties: {
            action: {
              type: "string",
              enum: ["get", "set", "reset"],
              description: "Action to perform: get current config, set new config, or reset to defaults",
            },
            config: {
              type: "object",
              description: "Configuration object (required for 'set' action)",
              properties: {
                chainMode: {
                  type: "string",
                  enum: ["strict_chain", "dynamic_chain", "random_chain", "round_robin_chain"],
                },
                dnsMode: {
                  type: "string",
                  enum: ["proxy_dns", "proxy_dns_old", "proxy_dns_daemon", "none"],
                },
                chainLen: {
                  type: "number",
                  description: "Chain length for random/round_robin modes",
                },
                tcpReadTimeout: {
                  type: "number",
                  description: "TCP read timeout in ms",
                },
                tcpConnectTimeout: {
                  type: "number",
                  description: "TCP connect timeout in ms",
                },
                quiet: {
                  type: "boolean",
                  description: "Suppress proxychains output",
                },
                proxies: {
                  type: "array",
                  items: {
                    type: "object",
                    properties: {
                      type: { type: "string", enum: ["http", "socks4", "socks5", "raw"] },
                      host: { type: "string" },
                      port: { type: "number" },
                      user: { type: "string" },
                      pass: { type: "string" },
                    },
                    required: ["type", "host", "port"],
                  },
                },
              },
            },
          },
          required: ["action"],
        },
      },
      {
        name: "proxychains_add",
        description: "Add a proxy to the chain. Supports SOCKS4, SOCKS5, and HTTP proxies.",
        inputSchema: {
          type: "object",
          properties: {
            type: {
              type: "string",
              enum: ["http", "socks4", "socks5", "raw"],
              description: "Proxy type",
            },
            host: {
              type: "string",
              description: "Proxy host/IP address",
            },
            port: {
              type: "number",
              description: "Proxy port",
            },
            user: {
              type: "string",
              description: "Username for authentication (optional)",
            },
            pass: {
              type: "string",
              description: "Password for authentication (optional)",
            },
            position: {
              type: "number",
              description: "Position in the chain (0-indexed). Defaults to end of list.",
            },
          },
          required: ["type", "host", "port"],
        },
      },
      {
        name: "proxychains_remove",
        description: "Remove a proxy from the chain by index or by host:port.",
        inputSchema: {
          type: "object",
          properties: {
            index: {
              type: "number",
              description: "Index of proxy to remove (0-indexed)",
            },
            host: {
              type: "string",
              description: "Host of proxy to remove",
            },
            port: {
              type: "number",
              description: "Port of proxy to remove (required if using host)",
            },
          },
        },
      },
      {
        name: "proxychains_mode",
        description:
          "Set the chain mode. strict_chain: all proxies must work. dynamic_chain: skip dead proxies. random_chain: random order. round_robin_chain: rotate through proxies.",
        inputSchema: {
          type: "object",
          properties: {
            mode: {
              type: "string",
              enum: ["strict_chain", "dynamic_chain", "random_chain", "round_robin_chain"],
              description: "Chain mode to use",
            },
            chainLen: {
              type: "number",
              description: "Number of proxies per connection (for random/round_robin modes)",
            },
          },
          required: ["mode"],
        },
      },
      {
        name: "proxychains_dns",
        description:
          "Configure DNS handling. proxy_dns (recommended): DNS through proxy. proxy_dns_old: legacy mode. proxy_dns_daemon: daemon mode. none: no DNS proxying.",
        inputSchema: {
          type: "object",
          properties: {
            mode: {
              type: "string",
              enum: ["proxy_dns", "proxy_dns_old", "proxy_dns_daemon", "none"],
              description: "DNS mode",
            },
          },
          required: ["mode"],
        },
      },
      {
        name: "proxychains_test",
        description:
          "Test the proxy chain by checking connectivity and measuring latency. Optionally test against a specific target.",
        inputSchema: {
          type: "object",
          properties: {
            target: {
              type: "string",
              description: "Target URL to test (default: https://httpbin.org/ip)",
            },
            verbose: {
              type: "boolean",
              description: "Show detailed output including response body",
            },
          },
        },
      },
      {
        name: "proxychains_list",
        description: "List all proxies currently configured in the chain.",
        inputSchema: {
          type: "object",
          properties: {},
        },
      },
      {
        name: "proxychains_import",
        description: "Import proxies from a file or URL. Supports common proxy list formats.",
        inputSchema: {
          type: "object",
          properties: {
            source: {
              type: "string",
              description: "File path or URL containing proxy list",
            },
            format: {
              type: "string",
              enum: ["auto", "proxychains", "ip:port", "type://ip:port"],
              description: "Format of the proxy list (default: auto-detect)",
            },
            defaultType: {
              type: "string",
              enum: ["http", "socks4", "socks5"],
              description: "Default proxy type if not specified in list (default: socks5)",
            },
          },
          required: ["source"],
        },
      },
      {
        name: "proxychains_export",
        description: "Export current proxy configuration to a file.",
        inputSchema: {
          type: "object",
          properties: {
            format: {
              type: "string",
              enum: ["proxychains", "json", "ip:port"],
              description: "Output format (default: proxychains)",
            },
          },
        },
      },
    ],
  };
});

// Handle tool calls
server.setRequestHandler(CallToolRequestSchema, async (request) => {
  const { name, arguments: args } = request.params;

  try {
    // Load config at start
    await loadConfig();

    switch (name) {
      case "proxychains_run": {
        const { command, timeout } = args as { command: string; timeout?: number };

        if (!command) {
          throw new McpError(ErrorCode.InvalidParams, "Command is required");
        }

        // Check if we have proxies configured
        if (currentConfig.proxies.length === 0) {
          return {
            content: [
              {
                type: "text",
                text: "Error: No proxies configured. Use proxychains_add to add proxies first.",
              },
            ],
          };
        }

        const startTime = Date.now();
        const result = await runWithProxychains(command);
        const elapsed = Date.now() - startTime;

        return {
          content: [
            {
              type: "text",
              text: `Command executed through proxy chain in ${elapsed}ms\n\n--- STDOUT ---\n${result.stdout}\n\n--- STDERR ---\n${result.stderr}`,
            },
          ],
        };
      }

      case "proxychains_config": {
        const { action, config } = args as {
          action: "get" | "set" | "reset";
          config?: Partial<ProxychainsConfig>;
        };

        if (action === "get") {
          return {
            content: [
              {
                type: "text",
                text: `Current configuration:\n${JSON.stringify(currentConfig, null, 2)}\n\nGenerated proxychains.conf:\n${generateProxychainsConf()}`,
              },
            ],
          };
        } else if (action === "set") {
          if (!config) {
            throw new McpError(ErrorCode.InvalidParams, "Config object required for 'set' action");
          }
          currentConfig = { ...currentConfig, ...config };
          await saveConfig();
          return {
            content: [
              {
                type: "text",
                text: `Configuration updated:\n${JSON.stringify(currentConfig, null, 2)}`,
              },
            ],
          };
        } else if (action === "reset") {
          currentConfig = { ...defaultConfig };
          await saveConfig();
          return {
            content: [
              {
                type: "text",
                text: "Configuration reset to defaults",
              },
            ],
          };
        }
        break;
      }

      case "proxychains_add": {
        const { type, host, port, user, pass, position } = args as {
          type: ProxyType;
          host: string;
          port: number;
          user?: string;
          pass?: string;
          position?: number;
        };

        const proxy: Proxy = { type, host, port };
        if (user) proxy.user = user;
        if (pass) proxy.pass = pass;

        if (position !== undefined && position >= 0 && position <= currentConfig.proxies.length) {
          currentConfig.proxies.splice(position, 0, proxy);
        } else {
          currentConfig.proxies.push(proxy);
        }

        await saveConfig();

        return {
          content: [
            {
              type: "text",
              text: `Added proxy: ${type} ${host}:${port}\nTotal proxies: ${currentConfig.proxies.length}`,
            },
          ],
        };
      }

      case "proxychains_remove": {
        const { index, host, port } = args as {
          index?: number;
          host?: string;
          port?: number;
        };

        let removedProxy: Proxy | undefined;

        if (index !== undefined) {
          if (index < 0 || index >= currentConfig.proxies.length) {
            throw new McpError(ErrorCode.InvalidParams, `Invalid index: ${index}`);
          }
          removedProxy = currentConfig.proxies.splice(index, 1)[0];
        } else if (host && port) {
          const idx = currentConfig.proxies.findIndex(
            (p) => p.host === host && p.port === port
          );
          if (idx === -1) {
            throw new McpError(ErrorCode.InvalidParams, `Proxy not found: ${host}:${port}`);
          }
          removedProxy = currentConfig.proxies.splice(idx, 1)[0];
        } else {
          throw new McpError(
            ErrorCode.InvalidParams,
            "Either index or host+port is required"
          );
        }

        await saveConfig();

        return {
          content: [
            {
              type: "text",
              text: `Removed proxy: ${removedProxy.type} ${removedProxy.host}:${removedProxy.port}\nRemaining proxies: ${currentConfig.proxies.length}`,
            },
          ],
        };
      }

      case "proxychains_mode": {
        const { mode, chainLen } = args as { mode: ChainMode; chainLen?: number };

        currentConfig.chainMode = mode;
        if (chainLen !== undefined) {
          currentConfig.chainLen = chainLen;
        }

        await saveConfig();

        return {
          content: [
            {
              type: "text",
              text: `Chain mode set to: ${mode}${chainLen ? ` (chain_len: ${chainLen})` : ""}`,
            },
          ],
        };
      }

      case "proxychains_dns": {
        const { mode } = args as { mode: DnsMode };

        currentConfig.dnsMode = mode;
        await saveConfig();

        return {
          content: [
            {
              type: "text",
              text: `DNS mode set to: ${mode}`,
            },
          ],
        };
      }

      case "proxychains_test": {
        const { target = "https://httpbin.org/ip", verbose = false } = args as {
          target?: string;
          verbose?: boolean;
        };

        if (currentConfig.proxies.length === 0) {
          return {
            content: [
              {
                type: "text",
                text: "Error: No proxies configured. Use proxychains_add to add proxies first.",
              },
            ],
          };
        }

        // Test connectivity
        const startTime = Date.now();
        try {
          const result = await runWithProxychains(`curl -s -o /dev/null -w "%{http_code}|%{time_total}" ${target}`);
          const elapsed = Date.now() - startTime;
          const [httpCode, curlTime] = result.stdout.trim().split("|");

          let response = `Proxy chain test results:\n`;
          response += `- Target: ${target}\n`;
          response += `- HTTP Status: ${httpCode}\n`;
          response += `- Total Time: ${elapsed}ms\n`;
          response += `- Curl Time: ${parseFloat(curlTime) * 1000}ms\n`;
          response += `- Chain Mode: ${currentConfig.chainMode}\n`;
          response += `- Proxies: ${currentConfig.proxies.length}\n`;

          if (verbose) {
            const verboseResult = await runWithProxychains(`curl -s ${target}`);
            response += `\n--- Response Body ---\n${verboseResult.stdout}`;
          }

          return {
            content: [
              {
                type: "text",
                text: response,
              },
            ],
          };
        } catch (error: any) {
          return {
            content: [
              {
                type: "text",
                text: `Proxy chain test FAILED:\n${error.message}\n\nThis could indicate:\n- One or more proxies are down (try dynamic_chain mode)\n- Network connectivity issues\n- Target is blocking proxy connections`,
              },
            ],
          };
        }
      }

      case "proxychains_list": {
        if (currentConfig.proxies.length === 0) {
          return {
            content: [
              {
                type: "text",
                text: "No proxies configured.\n\nUse proxychains_add to add proxies.",
              },
            ],
          };
        }

        let list = `Configured proxies (${currentConfig.proxies.length}):\n`;
        list += `Chain mode: ${currentConfig.chainMode}\n\n`;
        currentConfig.proxies.forEach((proxy, idx) => {
          list += `${idx}: ${proxy.type}\t${proxy.host}:${proxy.port}`;
          if (proxy.user) list += ` (auth: ${proxy.user})`;
          list += "\n";
        });

        return {
          content: [
            {
              type: "text",
              text: list,
            },
          ],
        };
      }

      case "proxychains_import": {
        const { source, format = "auto", defaultType = "socks5" } = args as {
          source: string;
          format?: "auto" | "proxychains" | "ip:port" | "type://ip:port";
          defaultType?: ProxyType;
        };

        let content: string;

        // Fetch content from URL or read from file
        if (source.startsWith("http://") || source.startsWith("https://")) {
          const result = await execAsync(`curl -s "${source}"`);
          content = result.stdout;
        } else {
          // Try to read from Kali
          const result = await executeOnKali(`cat "${source}"`);
          content = result.stdout;
        }

        const lines = content.split("\n").filter((line) => line.trim() && !line.startsWith("#"));
        const imported: Proxy[] = [];

        for (const line of lines) {
          let proxy: Proxy | null = null;

          // Try different formats
          // Format: type://host:port or type://user:pass@host:port
          const urlMatch = line.match(/^(http|socks4|socks5):\/\/(?:([^:]+):([^@]+)@)?([^:]+):(\d+)/);
          if (urlMatch) {
            proxy = {
              type: urlMatch[1] as ProxyType,
              host: urlMatch[4],
              port: parseInt(urlMatch[5], 10),
            };
            if (urlMatch[2]) proxy.user = urlMatch[2];
            if (urlMatch[3]) proxy.pass = urlMatch[3];
          }

          // Format: type host port [user] [pass]
          if (!proxy) {
            const pcMatch = line.match(/^(http|socks4|socks5|raw)\s+(\S+)\s+(\d+)(?:\s+(\S+))?(?:\s+(\S+))?/);
            if (pcMatch) {
              proxy = {
                type: pcMatch[1] as ProxyType,
                host: pcMatch[2],
                port: parseInt(pcMatch[3], 10),
              };
              if (pcMatch[4]) proxy.user = pcMatch[4];
              if (pcMatch[5]) proxy.pass = pcMatch[5];
            }
          }

          // Format: host:port
          if (!proxy) {
            const simpleMatch = line.match(/^(\S+):(\d+)$/);
            if (simpleMatch) {
              proxy = {
                type: defaultType,
                host: simpleMatch[1],
                port: parseInt(simpleMatch[2], 10),
              };
            }
          }

          if (proxy) {
            imported.push(proxy);
          }
        }

        currentConfig.proxies.push(...imported);
        await saveConfig();

        return {
          content: [
            {
              type: "text",
              text: `Imported ${imported.length} proxies from ${source}\nTotal proxies: ${currentConfig.proxies.length}`,
            },
          ],
        };
      }

      case "proxychains_export": {
        const { format = "proxychains" } = args as {
          format?: "proxychains" | "json" | "ip:port";
        };

        let output: string;

        switch (format) {
          case "proxychains":
            output = generateProxychainsConf();
            break;
          case "json":
            output = JSON.stringify(currentConfig, null, 2);
            break;
          case "ip:port":
            output = currentConfig.proxies.map((p) => `${p.host}:${p.port}`).join("\n");
            break;
          default:
            output = generateProxychainsConf();
        }

        return {
          content: [
            {
              type: "text",
              text: output,
            },
          ],
        };
      }

      default:
        throw new McpError(ErrorCode.MethodNotFound, `Unknown tool: ${name}`);
    }
  } catch (error: any) {
    if (error instanceof McpError) {
      throw error;
    }
    throw new McpError(ErrorCode.InternalError, error.message);
  }

  throw new McpError(ErrorCode.InternalError, "Unexpected code path");
});

// Main entry point
async function main() {
  await ensureConfigDir();
  await loadConfig();

  const transport = new StdioServerTransport();
  await server.connect(transport);

  console.error("Proxychains MCP server started");
}

main().catch((error) => {
  console.error("Fatal error:", error);
  process.exit(1);
});
